### ISSUE TITLE
Stepping onto unknown node leads to "attempt to index a nil value"

### ISSUE THREAD

**Issue by RichardTry** [sirrobzeroone/3d_armor_flyswim#3]
Stepping onto unknown node triggeres it.
```
AsyncErr: environment_Step: Runtime error from mod '' in callback environment_Step(): .minetest/mods/3d_armor_flyswim/init.lua:117: attempt to index a nil value
stack traceback:
	/mods/3d_armor_flyswim/init.lua:117: in function <.minetest/mods/3d_armor_flyswim/init.lua:106>
	/usr/share/games/minetest/builtin/game/register.lua:429: in function </usr/share/games/minetest/builtin/game/register.lua:413>
stack traceback:
```

**Comment by sirrobzeroone** [comment]
Thanks for the report just back from holidays so ill have a look over the next few days

**Comment by sirrobzeroone** [comment]
Okay got a fix for this one, basically I just need to catch for unregistered node names. The mods not really designed/intended to walk around on a bunch of unknown nodes, However I could see that happening during game development and it makes the code more robust which is always good. 

I'll wrap a minor fix and update to the code base in the next day or so I have to do further testing to make sure I didnt break soemthing else :)
