### ISSUE TITLE
Oups global variable created

### ISSUE THREAD

**Issue by mazes-80** [sirrobzeroone/3d_armor_flyswim#7]
Think this one needs local
<pre>
--- i_functions.lua
+++ i_functions.lua
@@ -52,6 +52,7 @@
                compare = draw_tl
        end
 
+       local_ndraw
        for k,v in pairs(nodes) do
                n_draw = minetest.registered_nodes[v.name].drawtype
                        for k2,v2 in ipairs(compare) do
</pre>

Sed fix:
`sed -i '55i    local_ndraw' i_functions.lua`

**Comment by sirrobzeroone** [comment]
Thanks heaps updated in code base, good pickup

**Comment by mazes-80** [comment]
Also another thing I figured out some days ago using apercy vehicles:
when you use the submarine, you get the animation switched to "swim", that make things quite weird, offset of camera isn't good ...
Could you check attachment to entities, as I guess if I attach my Sam to a horse, at one point when jumping the fly animation will be triggered. Or maybe the way back for other mods to force an animation until detached ?
Same appears for mod dealing with higher velocity, like lavastuff boots: those multiply z vel by 2 .
Checking for such would allow to trigger fly animation respecting those multipliers. to keep track of every different multiplier I use player_monoids which make thing coherent for many mods: local climate + lavastuff + hbsprint are interacting together perfectly.
I didn't dig enough your code to forge me an idea.

P.S.: discussions would be a better place to talk, but github don't open those automatically

**Comment by sirrobzeroone** [comment]
I'll have a look i know checking for on attach I could just do a break and then no animation. Wow fast boots, i cant remember if i explicitly check for downward velocity but I could add that check and/or see if monoids has a way to confirm whats multiplying the speed and similarly do a break.

**Comment by mazes-80** [comment]
There was a typo in my sed line !!!
change 'local_ndraw' to 'local n_draw'
sorry

**Comment by sirrobzeroone** [comment]
all good all fixed no stress :)

**Comment by mazes-80** [comment]
Yes, I was, ruin another's work because of a misaligned underscore is bad !!
